### ISSUE TITLE
'POSIXError' does not conform to 'ErrorType'

### ISSUE THREAD

**Issue by madhavajay** [PureSwift/SwiftFoundation#20]
I get this error when trying to compile on OSX with the latest swift 2.2 dec 31 snapshot.

Compiling Swift Module 'SwiftFoundation' (51 sources)
/SwiftFoundationExample/Packages/SwiftFoundation-1.1.0/Sources/SwiftFoundation/POSIXFileSystemStatus.swift:28:45: error: thrown expression type 'POSIXError' does not conform to 'ErrorType'
            throw POSIXError.fromErrorNumber!

**Comment by colemancda** [comment]
Building from Xcode with Carthage is the only supported method on Apple platforms. SPM is only supported for Linux.

**Comment by colemancda** [comment]
But, you're open to create a PR with the necessary changes, its just not one of my goals to support the SPM for OS X.

**Comment by madhavajay** [comment]
Okay, are you able to point me in any directions to figure it out, I assume its missing Darwin or something? Sorry i'm a Swift Open Source n00b but keen to get involved.

**Comment by colemancda** [comment]
Just clone the git repo, then open the `.xcodeproj` and compile.

**Comment by madhavajay** [comment]
No, for fixing SPM support on OSX. Any idea  it fails on the posix error? I assume its because it needs Darwin for POSIX support?

**Comment by colemancda** [comment]
Either missing Darwin, or make it conform with a `extension PosixError: ErrorType { }`

**Comment by madhavajay** [comment]
Okay cool thanks ill have a play around and if I can get it working ill make a PR. :)
